import numpy as np


#15 rectangles with the centers 24 degrees apart on the circumference of a circle
#and the sides 2 degrees offset from center, the value of inner_r is inversely correlated 
# to the size of the radius, smaller val -> larger radius
inner_r = 50
outer_r = 150
offset = 5
height = 25
# x = r * sin(theta = offset angle from origin clockwise)
# y = r * cos(theta)

#default offsets recenter the circles to the center of the box
def get_x(r, theta, x_offset = 12.5):
    return x_offset + (r * np.sin(theta * np.pi / 180.))

def get_y(r, theta, y_offset = 50.):
    return y_offset - (r * np.cos(theta * np.pi / 180.)) 

#points of the top of the box center piece the model is calibrated to
center_points = {'front_left' : np.array([0, 0, 1]),
                 'front_right' : np.array([25, 0, 1]),
                 'back_left' : np.array([0, 100, 1]),
                 'back_right' : np.array([25, 100, 1])}

outer_points = {'frame_a' : {'lft' :np.array([get_x(outer_r, 360 - offset), get_y(outer_r, 360 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, offset), get_y(outer_r, offset), 1])},
                'frame_b' : {'lft' : np.array([get_x(outer_r, 24 - offset), get_y(outer_r, 24 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 24 + offset), get_y(outer_r, 24 + offset), 1])},
                'frame_c' : {'lft' : np.array([get_x(outer_r, 48 - offset), get_y(outer_r, 48 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 48 + offset), get_y(outer_r, 48 + offset), 1])},
                'frame_d' : {'lft' : np.array([get_x(outer_r, 72 - offset), get_y(outer_r, 72 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 72 + offset), get_y(outer_r, 72 + offset), 1])},
                'frame_e' : {'lft' : np.array([get_x(outer_r, 96 - offset), get_y(outer_r, 96 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 96 + offset), get_y(outer_r, 96 + offset), 1])},
                'frame_f' : {'lft' : np.array([get_x(outer_r, 120 - offset), get_y(outer_r, 120 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 120 + offset), get_y(outer_r, 120 + offset), 1])},
                'frame_g' : {'lft' : np.array([get_x(outer_r, 144 - offset), get_y(outer_r, 144 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 144 + offset), get_y(outer_r, 144 + offset), 1])},
                'frame_h' : {'lft' : np.array([get_x(outer_r, 168 - offset), get_y(outer_r, 168 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 168 + offset), get_y(outer_r, 168 + offset), 1])},
                'frame_i' : {'lft' : np.array([get_x(outer_r, 192 - offset), get_y(outer_r, 192 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 192 + offset), get_y(outer_r, 192 + offset), 1])},
                'frame_j' : {'lft' : np.array([get_x(outer_r, 216 - offset), get_y(outer_r, 216 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 216 + offset), get_y(outer_r, 216 + offset), 1])},
                'frame_k' : {'lft' : np.array([get_x(outer_r, 240 - offset), get_y(outer_r, 240 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 240 + offset), get_y(outer_r, 240 + offset), 1])},
                'frame_l' : {'lft' : np.array([get_x(outer_r, 264 - offset), get_y(outer_r, 264 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 264 + offset), get_y(outer_r, 264 + offset), 1])},
                'frame_m' : {'lft' : np.array([get_x(outer_r, 288 - offset), get_y(outer_r, 288 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 288 + offset), get_y(outer_r, 288 + offset), 1])},
                'frame_n' : {'lft' : np.array([get_x(outer_r, 312 - offset), get_y(outer_r, 312 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 312 + offset), get_y(outer_r, 312 + offset), 1])},
                'frame_o' : {'lft' : np.array([get_x(outer_r, 336 - offset), get_y(outer_r, 336 - offset), 1]),
                             'rt' : np.array([get_x(outer_r, 336 + offset), get_y(outer_r, 336 + offset), 1])}}

outer_points_lower = {'frame_a' : {'lft' :np.array([get_x(outer_r, 360 - offset), get_y(outer_r, 360 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, offset), get_y(outer_r, offset), -height])},
                'frame_b' : {'lft' : np.array([get_x(outer_r, 24 - offset), get_y(outer_r, 24 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 24 + offset), get_y(outer_r, 24 + offset), -height])},
                'frame_c' : {'lft' : np.array([get_x(outer_r, 48 - offset), get_y(outer_r, 48 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 48 + offset), get_y(outer_r, 48 + offset), -height])},
                'frame_d' : {'lft' : np.array([get_x(outer_r, 72 - offset), get_y(outer_r, 72 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 72 + offset), get_y(outer_r, 72 + offset), -height])},
                'frame_e' : {'lft' : np.array([get_x(outer_r, 96 - offset), get_y(outer_r, 96 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 96 + offset), get_y(outer_r, 96 + offset), -height])},
                'frame_f' : {'lft' : np.array([get_x(outer_r, 120 - offset), get_y(outer_r, 120 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 120 + offset), get_y(outer_r, 120 + offset), -height])},
                'frame_g' : {'lft' : np.array([get_x(outer_r, 144 - offset), get_y(outer_r, 144 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 144 + offset), get_y(outer_r, 144 + offset), -height])},
                'frame_h' : {'lft' : np.array([get_x(outer_r, 168 - offset), get_y(outer_r, 168 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 168 + offset), get_y(outer_r, 168 + offset), -height])},
                'frame_i' : {'lft' : np.array([get_x(outer_r, 192 - offset), get_y(outer_r, 192 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 192 + offset), get_y(outer_r, 192 + offset), -height])},
                'frame_j' : {'lft' : np.array([get_x(outer_r, 216 - offset), get_y(outer_r, 216 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 216 + offset), get_y(outer_r, 216 + offset), -height])},
                'frame_k' : {'lft' : np.array([get_x(outer_r, 240 - offset), get_y(outer_r, 240 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 240 + offset), get_y(outer_r, 240 + offset), -height])},
                'frame_l' : {'lft' : np.array([get_x(outer_r, 264 - offset), get_y(outer_r, 264 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 264 + offset), get_y(outer_r, 264 + offset), -height])},
                'frame_m' : {'lft' : np.array([get_x(outer_r, 288 - offset), get_y(outer_r, 288 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 288 + offset), get_y(outer_r, 288 + offset), -height])},
                'frame_n' : {'lft' : np.array([get_x(outer_r, 312 - offset), get_y(outer_r, 312 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 312 + offset), get_y(outer_r, 312 + offset), -height])},
                'frame_o' : {'lft' : np.array([get_x(outer_r, 336 - offset), get_y(outer_r, 336 - offset), -height]),
                             'rt' : np.array([get_x(outer_r, 336 + offset), get_y(outer_r, 336 + offset), -height])}}

#x_offset here is determining the how much deviation from the center the radius
# of the circle needs to be considered, original design was two concentric flat circles but is now 
# only the inner points (circle) and a circle stacked on top of that vertically
inner_points = {'frame_a' : {'lft' : np.array([get_x(inner_r, 180, x_offset=outer_points['frame_a']['lft'][0]),
                                               get_y(inner_r, 180, y_offset=outer_points['frame_a']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 180, x_offset=outer_points['frame_a']['rt'][0]),
                                              get_y(inner_r, 180, y_offset=outer_points['frame_a']['rt'][1]), 1])},
                'frame_b' : {'lft' : np.array([get_x(inner_r, 204, x_offset=outer_points['frame_b']['lft'][0]),
                                               get_y(inner_r, 204, y_offset=outer_points['frame_b']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 204, x_offset=outer_points['frame_b']['rt'][0]),
                                              get_y(inner_r, 204, y_offset=outer_points['frame_b']['rt'][1]), 1])},
                'frame_c' : {'lft' : np.array([get_x(inner_r, 228, x_offset=outer_points['frame_c']['lft'][0]),
                                               get_y(inner_r, 228, y_offset=outer_points['frame_c']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 228, x_offset=outer_points['frame_c']['rt'][0]),
                                              get_y(inner_r, 228, y_offset=outer_points['frame_c']['rt'][1]), 1])},
                'frame_d' : {'lft' : np.array([get_x(inner_r, 252, x_offset=outer_points['frame_d']['lft'][0]),
                                               get_y(inner_r, 252, y_offset=outer_points['frame_d']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 252, x_offset=outer_points['frame_d']['rt'][0]),
                                              get_y(inner_r, 252, y_offset=outer_points['frame_d']['rt'][1]), 1])},
                'frame_e' : {'lft' : np.array([get_x(inner_r, 276, x_offset=outer_points['frame_e']['lft'][0]),
                                               get_y(inner_r, 276, y_offset=outer_points['frame_e']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 276, x_offset=outer_points['frame_e']['rt'][0]),
                                              get_y(inner_r, 276, y_offset=outer_points['frame_e']['rt'][1]), 1])},
                'frame_f' : {'lft' : np.array([get_x(inner_r, 300, x_offset=outer_points['frame_f']['lft'][0]),
                                               get_y(inner_r, 300, y_offset=outer_points['frame_f']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 300, x_offset=outer_points['frame_f']['rt'][0]),
                                              get_y(inner_r, 300, y_offset=outer_points['frame_f']['rt'][1]), 1])},
                'frame_g' : {'lft' : np.array([get_x(inner_r, 324, x_offset=outer_points['frame_g']['lft'][0]),
                                               get_y(inner_r, 324, y_offset=outer_points['frame_g']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 324, x_offset=outer_points['frame_g']['rt'][0]),
                                              get_y(inner_r, 324, y_offset=outer_points['frame_g']['rt'][1]), 1])},
                'frame_h' : {'lft' : np.array([get_x(inner_r, 348, x_offset=outer_points['frame_h']['lft'][0]),
                                               get_y(inner_r, 348, y_offset=outer_points['frame_h']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 348, x_offset=outer_points['frame_h']['rt'][0]),
                                              get_y(inner_r, 348, y_offset=outer_points['frame_h']['rt'][1]), 1])},
                'frame_i' : {'lft' : np.array([get_x(inner_r, 12, x_offset=outer_points['frame_i']['lft'][0]),
                                               get_y(inner_r, 12, y_offset=outer_points['frame_i']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 12, x_offset=outer_points['frame_i']['rt'][0]),
                                              get_y(inner_r, 12, y_offset=outer_points['frame_i']['rt'][1]), 1])},
                'frame_j' : {'lft' : np.array([get_x(inner_r, 36, x_offset=outer_points['frame_j']['lft'][0]),
                                               get_y(inner_r, 36, y_offset=outer_points['frame_j']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 36, x_offset=outer_points['frame_j']['rt'][0]),
                                              get_y(inner_r, 36, y_offset=outer_points['frame_j']['rt'][1]), 1])},
                'frame_k' : {'lft' : np.array([get_x(inner_r, 60, x_offset=outer_points['frame_k']['lft'][0]),
                                               get_y(inner_r, 60, y_offset=outer_points['frame_k']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 60, x_offset=outer_points['frame_k']['rt'][0]),
                                              get_y(inner_r, 60, y_offset=outer_points['frame_k']['rt'][1]), 1])},
                'frame_l' : {'lft' : np.array([get_x(inner_r, 84, x_offset=outer_points['frame_l']['lft'][0]),
                                               get_y(inner_r, 84, y_offset=outer_points['frame_l']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 84, x_offset=outer_points['frame_l']['rt'][0]),
                                              get_y(inner_r, 84, y_offset=outer_points['frame_l']['rt'][1]), 1])},
                'frame_m' : {'lft' : np.array([get_x(inner_r, 108, x_offset=outer_points['frame_m']['lft'][0]),
                                               get_y(inner_r, 108, y_offset=outer_points['frame_m']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 108, x_offset=outer_points['frame_m']['rt'][0]),
                                              get_y(inner_r, 108, y_offset=outer_points['frame_m']['rt'][1]), 1])},
                'frame_n' : {'lft' : np.array([get_x(inner_r, 132, x_offset=outer_points['frame_n']['lft'][0]),
                                               get_y(inner_r, 132, y_offset=outer_points['frame_n']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 132, x_offset=outer_points['frame_n']['rt'][0]),
                                              get_y(inner_r, 132, y_offset=outer_points['frame_n']['rt'][1]), 1])},
                'frame_o' : {'lft' : np.array([get_x(inner_r, 156, x_offset=outer_points['frame_o']['lft'][0]),
                                               get_y(inner_r, 156, y_offset=outer_points['frame_o']['lft'][1]), 1]),
                             'rt' : np.array([get_x(inner_r, 156, x_offset=outer_points['frame_o']['rt'][0]),
                                              get_y(inner_r, 156, y_offset=outer_points['frame_o']['rt'][1]), 1])}}

inner_points_upper = {'frame_a' : {'lft' : np.array([get_x(inner_r, 180, 
                                                    x_offset=outer_points['frame_a']['lft'][0]),
                                               get_y(inner_r, 180, 
                                                     y_offset=outer_points['frame_a']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 180, 
                                                    x_offset=outer_points['frame_a']['rt'][0]),
                                              get_y(inner_r, 180, 
                                                    y_offset=outer_points['frame_a']['rt'][1]), height])},
                'frame_b' : {'lft' : np.array([get_x(inner_r, 204, 
                                                     x_offset=outer_points['frame_b']['lft'][0]),
                                               get_y(inner_r, 204, 
                                                     y_offset=outer_points['frame_b']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 204, 
                                                    x_offset=outer_points['frame_b']['rt'][0]),
                                              get_y(inner_r, 204, 
                                                    y_offset=outer_points['frame_b']['rt'][1]), height])},
                'frame_c' : {'lft' : np.array([get_x(inner_r, 228, 
                                                     x_offset=outer_points['frame_c']['lft'][0]),
                                               get_y(inner_r, 228, 
                                                     y_offset=outer_points['frame_c']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 228, 
                                                    x_offset=outer_points['frame_c']['rt'][0]),
                                              get_y(inner_r, 228, 
                                                    y_offset=outer_points['frame_c']['rt'][1]), height])},
                'frame_d' : {'lft' : np.array([get_x(inner_r, 252, 
                                                     x_offset=outer_points['frame_d']['lft'][0]),
                                               get_y(inner_r, 252, 
                                                     y_offset=outer_points['frame_d']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 252, 
                                                    x_offset=outer_points['frame_d']['rt'][0]),
                                              get_y(inner_r, 252, 
                                                    y_offset=outer_points['frame_d']['rt'][1]), height])},
                'frame_e' : {'lft' : np.array([get_x(inner_r, 276, 
                                                     x_offset=outer_points['frame_e']['lft'][0]),
                                               get_y(inner_r, 276, 
                                                     y_offset=outer_points['frame_e']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 276, 
                                                    x_offset=outer_points['frame_e']['rt'][0]),
                                              get_y(inner_r, 276, 
                                                    y_offset=outer_points['frame_e']['rt'][1]), height])},
                'frame_f' : {'lft' : np.array([get_x(inner_r, 300, 
                                                     x_offset=outer_points['frame_f']['lft'][0]),
                                               get_y(inner_r, 300, 
                                                     y_offset=outer_points['frame_f']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 300, 
                                                    x_offset=outer_points['frame_f']['rt'][0]),
                                              get_y(inner_r, 300, 
                                                    y_offset=outer_points['frame_f']['rt'][1]), height])},
                'frame_g' : {'lft' : np.array([get_x(inner_r, 324, 
                                                     x_offset=outer_points['frame_g']['lft'][0]),
                                               get_y(inner_r, 324, 
                                                     y_offset=outer_points['frame_g']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 324, 
                                                    x_offset=outer_points['frame_g']['rt'][0]),
                                              get_y(inner_r, 324, 
                                                    y_offset=outer_points['frame_g']['rt'][1]), height])},
                'frame_h' : {'lft' : np.array([get_x(inner_r, 348, 
                                                     x_offset=outer_points['frame_h']['lft'][0]),
                                               get_y(inner_r, 348, 
                                                     y_offset=outer_points['frame_h']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 348, 
                                                    x_offset=outer_points['frame_h']['rt'][0]),
                                              get_y(inner_r, 348, 
                                                    y_offset=outer_points['frame_h']['rt'][1]), height])},
                'frame_i' : {'lft' : np.array([get_x(inner_r, 12, 
                                                     x_offset=outer_points['frame_i']['lft'][0]),
                                               get_y(inner_r, 12,
                                                     y_offset=outer_points['frame_i']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 12, 
                                                    x_offset=outer_points['frame_i']['rt'][0]),
                                              get_y(inner_r, 12, 
                                                    y_offset=outer_points['frame_i']['rt'][1]), height])},
                'frame_j' : {'lft' : np.array([get_x(inner_r, 36, 
                                                     x_offset=outer_points['frame_j']['lft'][0]),
                                               get_y(inner_r, 36, 
                                                     y_offset=outer_points['frame_j']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 36, 
                                                    x_offset=outer_points['frame_j']['rt'][0]),
                                              get_y(inner_r, 36, 
                                                    y_offset=outer_points['frame_j']['rt'][1]), height])},
                'frame_k' : {'lft' : np.array([get_x(inner_r, 60, 
                                                     x_offset=outer_points['frame_k']['lft'][0]),
                                               get_y(inner_r, 60, 
                                                     y_offset=outer_points['frame_k']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 60, 
                                                    x_offset=outer_points['frame_k']['rt'][0]),
                                              get_y(inner_r, 60, 
                                                    y_offset=outer_points['frame_k']['rt'][1]), height])},
                'frame_l' : {'lft' : np.array([get_x(inner_r, 84, 
                                                     x_offset=outer_points['frame_l']['lft'][0]),
                                               get_y(inner_r, 84, 
                                                     y_offset=outer_points['frame_l']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 84, 
                                                    x_offset=outer_points['frame_l']['rt'][0]),
                                              get_y(inner_r, 84, 
                                                    y_offset=outer_points['frame_l']['rt'][1]), height])},
                'frame_m' : {'lft' : np.array([get_x(inner_r, 108, 
                                                     x_offset=outer_points['frame_m']['lft'][0]),
                                               get_y(inner_r, 108, 
                                                     y_offset=outer_points['frame_m']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 108, 
                                                    x_offset=outer_points['frame_m']['rt'][0]),
                                              get_y(inner_r, 108, 
                                                    y_offset=outer_points['frame_m']['rt'][1]), height])},
                'frame_n' : {'lft' : np.array([get_x(inner_r, 132, 
                                                     x_offset=outer_points['frame_n']['lft'][0]),
                                               get_y(inner_r, 132, 
                                                     y_offset=outer_points['frame_n']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 132, 
                                                    x_offset=outer_points['frame_n']['rt'][0]),
                                              get_y(inner_r, 132, 
                                                    y_offset=outer_points['frame_n']['rt'][1]), height])},
                'frame_o' : {'lft' : np.array([get_x(inner_r, 156, 
                                                     x_offset=outer_points['frame_o']['lft'][0]),
                                               get_y(inner_r, 156, 
                                                     y_offset=outer_points['frame_o']['lft'][1]), height]),
                             'rt' : np.array([get_x(inner_r, 156, 
                                                    x_offset=outer_points['frame_o']['rt'][0]),
                                              get_y(inner_r, 156, 
                                                    y_offset=outer_points['frame_o']['rt'][1]), height])}}
